### ISSUE TITLE
Discussion of website implementation / updates

### ISSUE THREAD

**Issue by ionlights** [ucfai/bot#17]
Semi-public discussion on some changes to be made to the website – https://ucfai.org/

**Comment by SirRoboto** [comment]
Here are the things I would like to see added to the website:

*1. Sign-in button for members

- This includes being redirected to whatever feedback page we provide, confirming their attendance and allotting appropriate GPU hours
- Could perhaps give them a list of available options, including but not limited to: Checking the number of available GPU hours, reviewing previous feedback submissions, accessing the feedback submission page directly, checking their own personal account information
- Button should be available from any screen on the website as part of a menu bar at the top

2. Links to our other content

- This includes but is not limited to our Facebook page, Instagram profile, Github repos, Knightconnect page, and Discord. While the Github repos can be accessed to some degree through Course and Intelligence pages, I'd like to see permanent links to the home pages
- These links can either be provided at the bottom of the home page or be accessed on a separate through a general menu option

3. An actual menu bar from the main page

- As said above, a bar with potential drop-down to access general things like "Contact Us," "Meet our Team," "See our other content," "View our groups" (though redundant as groups are displayed on the home page already, this gives even more flexibility in navigating), etc. 
- The bar should persist regardless of the page the user is on
- Can be linked with the menu bar accessed from the /course and /intelligence pages

4. Meet our Team and Contact Us pages

- Both I imagine are relatively self-explanatory, where "Meet our Team" is pictures of the members as well as the current officers (which could include descriptions of our roles and a blurb about us), and Contact Us is the proper methods to reach us with questions

5. A slide deck window on the front page to display some general pictures

- Like a lot of websites, it simply shows off our team

6. A page to view our recent announcements (possible cross-implementation with a discord bot)

- Basically, an announcement made by a director or president on Discord can be pushed to the bot which then takes it to the website, displaying it either directly on the home page or some announcements page
- The idea is that we provide important information such as dates for meetings on as many platforms as possible
- This could also include the same for Instagram and Facebook

*7. Updating our wordage from the main page, including a more detailed description of our vision
- Course corrected to Core
- Plan to add Data Science blurb changed to actually having Data Science
- Vision should include a link to a potential more detailed outline of our vision and how we intend/see ourselves following it

*8. Releasing Data Science
- Currently not present from the home screen but should be there with Core and Intelligence


*Note: We've already discussed these items, or at least some version of them, prior to this post here, meaning they aren't necessarily novel but worthwhile to deliberate more on and continue keeping at our focus.

These items aren't ranked in any order of importance but rather things to throw out. **If we are focusing our efforts on specific tasks, I would stress the importance of items 1, 3, 7 and 8.**

This list is also not exhaustive, but simply the things that come to mind when I consider quality-of-life implementations and things you would generally expect for a club that utilizes quite a few independent platforms. This allows students to come to the website and access everything they need directly through there.

**Comment by ionlights** [comment]
> 1. Sign-in button for members

Sure, this makes sense to have and will definitely be implemented once the authenticator is properly setup. We'll chat about this in the meeting today (Aug 14).

> 2. Links to our other content

Agreed, though placement of all these links will take some time – as having a tidy navigation is ideal. Makes for less confusion. We may need to have a "hamburger menu" (think the 3 horizontal line menus in apps like those from Google) to store all our links.

I definitely think we should have the places we **want the most interaction** on the navbar itself.

They should definitely be in a footer, as should a sitemap, but I'd say that's a lower priority right now, as we need to figure out how we want the sitemap to be laid out (e.g. enumerating semesters, etc.).

> 3. An actual menu bar from ~the main page~ **all pages**

This definitely needs to be there, when I initially built the site it was an afterthought because I didn't have time to put thought into designing it.

> 4. Meet our Team and Contact Us pages

**Meet our Team:** We have something like that for Coordinators. How is this different? Also, should these be longer-term, in the sense that people can go back to a specific semester and see the Coordinators from that semester? Should we not care about that? (I disagree on the last bit.)

**Contact Us:** Should there be a form on the page? If so, why? What are you thinking of putting here? A page with just social links and an email is going to be very sparse, so what else might we put here? What if we combined it with an "About Us" or something of the like?

> 5. A slide deck window on the front page to display some general pictures

You wanna get rid of `particles.js`? 😢 

> 6. A page to view our recent announcements (possible cross-implementation with a discord bot)

This is good, it was something previously discussed between @dibaccory and I – but this would actually take quite a bit of time to get it fully-functional. I think this is something to table until later in the Fall – as it requires dissecting the Discord, Instagram, and Facebook APIs (if we can auto-post on the latter two – I think they may prevent that now). **NB:** There are other ways to do this than using the APIs, but it's a bit more of a pain. Also, we can xpost on Instagram/Facebook, so may we just need to write it up on Instagram and Facebook will be sorted? *This should also include email blasts.*

> 7. Updating our wordage from the main page, including a more detailed description of our vision

Sure, I believe we have a lot of that already documented someone in the abyss that is Google Drive, but it wouldn't be bad to have it somewhat immortalized on the site.

> 8. Releasing Data Science

LOL. Y'don't say. 😅 

**Major takeaway:** Previously, I tried to make a regular structure among groups, semesters, and the like. It seems we may need to discern some monolithic structure which can be use for the more generic things, like "Meet our Team," "About Us," etc. That may not be something easily injectable into the current site design – but we should have all this data present which means it *just* requires re-architecting.

**Comment by SirRoboto** [comment]
**Note:** Items are listed in order of priority first and broken down based on **Content** (denoted by “**C**”) and **Style** changes (denoted by “**S**”). If any of the items have “**TBD**” in them, then feel free to give them little head space, for now. 

While the specific verbiage itself is not detailed here, this should help distinguish between additions of text and additions of pages/reorganization of content. 

1.	Updating wordage for main page
     a.	Course corrected to Core – C
     b.	Change of main blurb to accurately represent the release of Data Science – C
     c.	Vision statement should be expanded on – C
              i.	Consider a link such as “Read More” to take them to that expanded explanation – S

2.	Releasing Data Science
     a.	Wordage to give a summary of Data Science – C
              i.	Data Science box appears beside Core and Intelligence – S
     b.	Data Science space should be formatted similar or use the same format/navigation as Core and Intelligence (aside from some extra additions such as competitions, which are TBD) – S

3.	Sign-in button for members
     a.	“Sign in” text from Core, Data Science, and Intelligence pages – C
              i.	Functionality of Sign-in button to redirect them to their respective account/update their attendance – S
     b.	Possibility of including an account page with details on GPU hours, submissions, feedback, and personal info put in when they registered (TBD) - C/S

4.	Menu bar/hamburger menu
     a.	Items on hamburger menu
              i.	Meet our Team – C
                     1.	Like how we have coordinators displayed, we have a dedicated, archived space for current and past officers with their position and photo – S
             ii.	Other Resources (listed on hamburger menu) – C 
                     1.	Should include links to Discord, Github, Instagram, and Facebook (for now) – S
            iii.	Announcements Page (TBD) – C
                     1.	We should hold off on this item, but it would most likely pull the announcements from somewhere else – S 
            iv.	Possible About Us (TBD) – C
                     1.	Instead of expanding the vision statement in a “Read More” from the landing page, we could instead put it on our About Us page, or rather only have them navigate to the “About Us” through the menu bar – C/S
     b.	Menu bar persists either (TBD):
              i.	Everywhere, including the landing page, OR – S 
             ii.	Everywhere, excluding the landing page – S 
     c.	“Home” button on menu bar for all pages – C/S

5.	“Sponsor Us” button
     a.	Appropriate page that includes a link to the sponsorship package or some coverage of the material in a condensed format, or some combination of both – C/S
     b.	Button should fall below the fold, or at the bottom of the page – S 
     c.	Should be available from every page, including the landing page – S 

6.	Implemented slide deck from Instagram – S 
     a.	Includes Pictures – S 
     b.	Could do something similar for announcements (TBD) – C/S
     c.	Can be located on landing page in a way where it doesn’t affect particles.js – S

**Comment by ionlights** [comment]
1. Updating wordage for main page
   1. `C`: Course corrected to Core 
`_data/groups.yml`
   1. `C`: Change of main blurb to accurately represent the release of Data Science
`index.md`
   1. `C`: Vision statement should be expanded on
`index.md`
      1. `S`: Consider a link such as “Read More” to take them to that expanded explanation
`index.md`

1. Releasing Data Science
   1. `C`: Wordage to give a summary of Data Science
`_data/groups.yml`
      1. `C`: Data Science box appears beside Core and Intelligence
`_data/semesters/fa19.yml` (make this and copy the structure of `sp19.yml`)
   1. **`TBD`** `C`: Data Science space should be formatted similar or use the same format/navigation as Core and Intelligence (aside from some extra additions such as competitions, which are TBD)
    > **Not sure what you mean here**, are you talking about the page which would be at `/data-science/`?

1. Sign-in button for members
   > The following section, honestly, should be characterized under `S` more than `C`. 😅 
   1. `C`: “Sign in” text from Core, Data Science, and Intelligence pages
      1. `S`: Functionality of Sign-in button to redirect them to their respective account/update their attendance
   1. **`TBD`** `C/S`: Possibility of including an account page with details on GPU hours, submissions, feedback, and personal info put in when they registered

1. Menu bar/hamburger menu 
   > The following section, honestly, should be characterized under `S` more than `C`. 😅 
   1. Items on hamburger menu
      1. `C`: Meet our Team
         1. `S`: Like how we have coordinators displayed, we have a dedicated, archived space for current and past officers with their position and photo
      1. `C`: Other Resources (listed on hamburger menu)
         1. `S`: Should include links to Discord, Github, Instagram, and Facebook (for now)
      1. **`TBD`** `C`: Announcements Page
         1. `S`: We should hold off on this item, but it would most likely pull the announcements from somewhere else
      1. **`TBD`** `C`: Possible About Us
         1. `C/S`: Instead of expanding the vision statement in a “Read More” from the landing page, we could instead put it on our About Us page, or rather only have them navigate to the “About Us” through the menu bar

   1. **`TBD`** Menu bar persists either:
      1. `S`: Everywhere, including the landing page, OR
      1. `S`: Everywhere, excluding the landing page
   1. `C/S`: “Home” button on menu bar for all pages

1. “Sponsor Us” button
   1. `C/S`: Appropriate page that includes a link to the sponsorship package or some coverage of the material in a condensed format, or some combination of both
   1. `S`: Button should fall below the fold, or at the bottom of the page
   1. `C`: Should be available from every page, including the landing page
       > On other pages, maybe it can go in the navbar? That seems reasonable, considering what most open-source projects do. Main "gripe" I had was on the homepage.

1. `S`: Implemented slide deck from Instagram
   > **Where should this go?** Homepage? 
   1. `S`: Includes Pictures
   1. **`TBD`** `C/S`: Could do something similar for announcements
   1. `S`: Can be located on landing page in a way where it doesn’t affect particles.js

**Comment by SirRoboto** [comment]
So, anywhere you feel it should be more S than C, I only put C down because I considered that both those items (3. and 4.) may require some text/descriptions implemented among their respective pages and items, but I agree that it is primarily S. 

2. ii. Correct, I'm talking about what's under /data-science/
5. iii. navbar being where home currently sits on other pages? I'm still concerned that if sponsors can't immediately grab it when coming to the webpage, then it won't really serve us
6. Yes, I was thinking the home page

**Comment by ionlights** [comment]
> 2. iii. navbar being where home currently sits on other pages? I'm still concerned that if sponsors can't immediately grab it when coming to the webpage, then it won't really serve us

So, on the homepage the button would still be there, but in a different place from the navbar. On all **other** pages, it would be on the navbar. That's what I'm thinking.
